### ISSUE TITLE
solve word_form module issue

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#22]
```py
import nltk
nltk.download('omw-1.4')
```
this depencency didnt auto download in setup.py while installing module through `pip`
need to solve by maybe moving it to ` ./module` to edit

**Comment by lmjaedentai** [comment]
try deleting and re-identify problem

**Comment by lmjaedentai** [comment]
seems module dev fix it
still under observation 👀

**Comment by lmjaedentai** [comment]
想太美   https://t.me/kaichengbotlab/5702

```py
  Resource  [93momw-1.4 [0m not found.
  Please use the NLTK Downloader to obtain the resource:

   [31m>>> import nltk
  >>> nltk.download('omw-1.4')
   [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load  [93mcorpora/omw-1.4 [0m

  Searched in:
    - '/app/nltk_data'
    - '/app/.heroku/python/nltk_data'
    - '/app/.heroku/python/share/nltk_data'
    - '/app/.heroku/python/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'



Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource  [93momw-1.4 [0m not found.
  Please use the NLTK Downloader to obtain the resource:

   [31m>>> import nltk
  >>> nltk.download('omw-1.4')
   [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load  [93mcorpora/omw-1.4.zip/omw-1.4/ [0m

  Searched in:
    - '/app/nltk_data'
    - '/app/.heroku/python/nltk_data'
    - '/app/.heroku/python/share/nltk_data'
    - '/app/.heroku/python/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 45, in inner
    await func(app,message,**kwargs)
  File "/app/main.py", line 145, in dictionary
    zh = cndict(lemmatize(search)) #try base form / lemma word
  File "/app/.heroku/python/lib/python3.9/site-packages/word_forms/lemmatizer.py", line 8, in lemmatize
    forms = [word for pos_form in get_word_forms(word).values() for word in pos_form]
  File "/app/.heroku/python/lib/python3.9/site-packages/word_forms/word_forms.py", line 93, in get_word_forms
    for pos in [wn.NOUN, wn.ADJ, wn.VERB, wn.ADV]
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/app/.heroku/python/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource  [93momw-1.4 [0m not found.
  Please use the NLTK Downloader to obtain the resource:

   [31m>>> import nltk
  >>> nltk.download('omw-1.4')
   [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load  [93mcorpora/omw-1.4 [0m

  Searched in:
    - '/app/nltk_data'
    - '/app/.heroku/python/nltk_data'
    - '/app/.heroku/python/share/nltk_data'
    - '/app/.heroku/python/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

```

**Comment by lmjaedentai** [comment]
fixed
```py
import nltk
nltk.download('omw-1.4')
```
just need to run once on setup
to let the server / pc download `nltk` once in their directory

**Comment by lmjaedentai** [comment]
But repl.it needs to run everytime after booting
It will reset all saved files in system directory

**Comment by lmjaedentai** [comment]
![Screenshot_2022-10-24-15-20-34-14_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/63090071/197469682-d7027cfd-a879-4f33-b562-b45e848fcfc5.jpg)

**Comment by lmjaedentai** [comment]
I thought i fixed??
