### ISSUE TITLE
Google trans api bug

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#25]
https://github.com/lushan88a/google_trans_new/pull/58 

maybe need to stop using my fix ver 
replace with this 

to fix 
`google_trans_new.google_new_transError: 404 (Not Found) from TTS API. Probable cause: Unknown`

**Comment by lmjaedentai** [comment]
```py

Traceback (most recent call last):
  File "/home/runner/billy-telegram/module/google_trans_new/google_trans_new.py", line 189, in translate
    r.raise_for_status()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://translate.google.cn/_/TranslateWebserverUi/data/batchexecute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 51, in inner
    await func(app,message,**kwargs)
  File "main.py", line 167, in kamus
    zh = translator.translate(query.text,lang_tgt='zh')
  File "/home/runner/billy-telegram/module/google_trans_new/google_trans_new.py", line 194, in translate
    raise google_new_transError(tts=self, response=r)
module.google_trans_new.google_trans_new.google_new_transError: 404 (Not Found) from TTS API. Probable cause: Unknown


```

**Comment by lmjaedentai** [comment]
replace with latest ver of module
havent upload to pypi ([8d0ba1b](https://github.com/lushan88a/google_trans_new/commit/8d0ba1bc4d2508fd304456386862ed034efceb4b)

**Comment by lmjaedentai** [comment]
https://nekobin.com/jitegeteya.py
