### ISSUE TITLE
Lyricsgenius API bug

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#31]
In error_handling() func add an exception `pyrogram.error`

~~1. https://stackoverflow.com/questions/72078610/getting-lyrics-from-genius-api-gives-error~~
2. https://github.com/johnwmillr/LyricsGenius/discussions/191

**Comment by lmjaedentai** [comment]
@lmjaedentai

**Comment by lmjaedentai** [comment]
partially fixed

```py
        except errors as error:
            fullerror = "".join(traceback.TracebackException.from_exception(error).format())
            printerror = await app.send_message(-1001518766606,f'❌ **{error}**\n```\n{fullerror}\n```#error', disable_web_page_preview=True)
            await app.send_message(message.chat.id,f"⁉️ **[Telegram API error]({printerror.link})**\n\nWe are sorry for that   /help", disable_web_page_preview=True)
            traceback.print_exception(type(error), error, error.__traceback__, file = sys.stderr)
```


still identifying why this happen

```py
Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/lyricsgenius/api/base.py", line 80, in _make_request
    response.raise_for_status()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=%E5%A5%B9%E7%9A%84%E7%9D%AB%E6%AF%9B

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 48, in inner
    await func(app,message,**kwargs)
  File "main.py", line 176, in findlyrics
    lyrics = genius.search_song(query.text, get_full_info=True)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/lyricsgenius/genius.py", line 401, in search_song
    search_response = self.search_all(search_term)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/lyricsgenius/api/public_methods/search.py", line 210, in search_all
    return self.search(search_term, per_page, page, endpoint)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/lyricsgenius/api/public_methods/search.py", line 45, in search
    return self._make_request(path, params_=params, public_api=True)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/lyricsgenius/api/base.py", line 88, in _make_request
    raise HTTPError(response.status_code, error)
requests.exceptions.HTTPError: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=%E5%A5%B9%E7%9A%84%E7%9D%AB%E6%AF%9B
```

**Comment by lmjaedentai** [comment]
https://stackoverflow.com/questions/72078610/getting-lyrics-from-genius-api-gives-error

**Comment by lmjaedentai** [comment]
Searching for "她的睫毛"...
catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "main.py", line 54, in inner
    await func(app,message,**kwargs)
  File "main.py", line 192, in findlyrics
    if lyrics is None:
UnboundLocalError: local variable 'lyrics' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "main.py", line 55, in inner
    except errors as error:
TypeError: catching classes that do not inherit from BaseException is not allowed
172.18.0.1 - - [24/Oct/2022 23:46:56] "GET / HTTP/1.1" 200 -
foo 1666655224.6770697
foo 1666655284.6745546
Searching for "她的睫毛"...
catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "main.py", line 54, in inner
    await func(app,message,**kwargs)
  File "main.py", line 192, in findlyrics
    if lyrics is None:
UnboundLocalError: local variable 'lyrics' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "main.py", line 55, in inner
    except errors as error:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by lmjaedentai** [comment]
https://github.com/Techcatchers/PyLyrics-Extractor

**Comment by lmjaedentai** [comment]
Fixed w switching to ytmusicapi 
https://github.com/lmjaedentai/billy-telegram/commit/6830df21ab22ff2376cfb6fc426a0c27cd740298

**Comment by lmjaedentai** [comment]
https://github.com/lmjaedentai/billy-telegram/commit/6830df21ab22ff2376cfb6fc426a0c27cd740298
