### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#33]
```py
Searching for "她的睫毛"...
catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "main.py", line 54, in inner
    await func(app,message,**kwargs)
  File "main.py", line 192, in findlyrics
    if lyrics is None:
UnboundLocalError: local variable 'lyrics' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "main.py", line 55, in inner
    except errors as error:
TypeError: catching classes that do not inherit from BaseException is not allowed
172.18.0.1 - - [24/Oct/2022 23:46:56] "GET / HTTP/1.1" 200 -
foo 1666655224.6770697
foo 1666655284.6745546
Searching for "她的睫毛"...
catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "main.py", line 54, in inner
    await func(app,message,**kwargs)
  File "main.py", line 192, in findlyrics
    if lyrics is None:
UnboundLocalError: local variable 'lyrics' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "main.py", line 55, in inner
    except errors as error:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by lmjaedentai** [comment]
if `try` fail, lyrics isnt defined in `if lyrics`
FIXED ✅

```py
    try:
        lyrics = genius.search_song(query.text, get_full_info=True)
    except:
        await app.send_message(message.chat.id,f"☹️ No search result\n\n **or**\n\n**[😀 Try Mojim.com](https://mojim.com/{query.text.replace(' ','%20')}.html?g3)**")#,reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("🔎 Try Google.",url=f"https://www.google.com/search?q={query.text.replace(' ','%20')}%20lyrics")]]))
    if lyrics is None:
        await app.send_message(message.chat.id,f"☹️ No search result\n\n **or**\n\n**[😀 Mojim.com](https://mojim.com/{query.text.replace(' ','%20')}.html?g3)**")#,reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("🔎 Try Google.",url=f"https://www.google.com/search?q={query.text.replace(' ','%20')}%20lyrics")]]))
    else:
        response = telegraph.create_page(query.text, html_content='🎸'+lyrics.lyrics.replace("\n", "<br>").replace("Lyrics", "<br>").replace("You might also like", "<br>").replace("Embed", "<br>") , author_name=lyrics.primary_artist.name, author_url=lyrics.primary_artist.url.replace(' ','%20'))
        await app.send_message(message.chat.id,response['url'],reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("🎧 listen",url=f"https://www.youtube.com/results?search_query={query.text}".replace(' ','%20'))],[InlineKeyboardButton("not this one ☹️",url=f"https://mojim.com/{query.text.replace(' ','%20')}.html?g3")]]))
    await typing.delete()
```

_Originally posted by @lmjaedentai in https://github.com/lmjaedentai/billy-telegram/issues/31#issuecomment-1289791151_
