### ISSUE TITLE
Billy dict fail handle paragraph 

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#56]
```py
❌ 'NoneType' object has no attribute 'from_user'

Traceback (most recent call last):
  File "main.py", line 60, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 172, in on_message
    if message.reply_to_message.from_user.id != me.id:
AttributeError: 'NoneType' object has no attribute 'from_user'

#error
```

![IMG_20230213_101410_344](https://user-images.githubusercontent.com/63090071/218355436-d98e0c5e-3ab5-43e0-9b85-c5906d9633b7.jpg)

**Comment by lmjaedentai** [comment]
https://github.com/lmjaedentai/billy-telegram/commit/d7e4e43d17c9755461beee8c5411ac3ca1fb4adb
