### ISSUE TITLE
/y query err handling fail

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#58]
```py

Traceback (most recent call last):
  File "main.py", line 55, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 263, in downloadyt
    await query.reply_document(f"./{music['fulltitle']}.mp3",force_document=False,reply_markup=ReplyKeyboardRemove())
KeyError: 'fulltitle'
```

![Screenshot_2023-02-13-10-17-02-56_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/63090071/218355875-5a0eaa5c-e23d-4477-a3c1-afc9d8ad8b11.jpg)

**Comment by lmjaedentai** [comment]
https://github.com/lmjaedentai/billy-telegram/commit/d7e4e43d17c9755461beee8c5411ac3ca1fb4adb
