### ISSUE TITLE
Popcat.xyz not reliable

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#64]
Maybe cause by `429` or `404`

```py
Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 60, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 403, in sendweather
    raw = response.json()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

![Screenshot_2023-02-19-09-52-31-74_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/63090071/219907908-63934dd7-7550-43cc-a2e7-031a3841c3b3.jpg)

**Comment by lmjaedentai** [comment]
```py
Traceback (most recent call last):
  File "main.py", line 60, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 501, in on_message
    await memecmd(int(row['type']),row['action'])
  File "main.py", line 489, in memecmd
    image = imgur_client.image_upload(result, 'Untitled', 'My first image upload')          #upload to imgur
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/imgur_python/Imgur.py", line 254, in image_upload
    return self.image.upload(payload, files)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/imgur_python/Image.py", line 60, in upload
    return self.response(request, url)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/imgur_python/ImgurBase.py", line 22, in response
    raise ExceptionLUT.get(request.status_code, ImgurException) \
imgur_python.Exceptions.ImgurException: (429, 'Too Many Requests')
```

**Comment by lmjaedentai** [comment]
start using openweatherapi

**Comment by lmjaedentai** [comment]
@lmjaedentai https://openweathermap.org/weather-conditions

**Comment by lmjaedentai** [comment]
@lmjaedentai https://openweathermap.org/forecast5

**Comment by lmjaedentai** [comment]
@lmjaedentai https://openweathermap.org/full-price#current

**Comment by lmjaedentai** [comment]
@lmjaedentai https://openweathermap.org/api/one-call-api
