### ISSUE TITLE
File naming decoding error in /y mp3

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#67]
❌ Failed to decode "./Brahms Lullaby 🎶 Best for Sleepy Baby |  Love Light.mp3". The value does not represent an existing local file, HTTP URL, or valid file id.

```py
Traceback (most recent call last):
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/base64.py", line 37, in _bytes_from_decode_data
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f3b6' in position 17: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/utils.py", line 49, in get_input_media_from_file_id
    decoded = FileId.decode(file_id)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/file_id.py", line 201, in decode
    decoded = rle_decode(b64_decode(file_id))
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/file_id.py", line 54, in b64_decode
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/base64.py", line 131, in urlsafe_b64decode
    s = _bytes_from_decode_data(s)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/base64.py", line 39, in _bytes_from_decode_data
    raise ValueError('string argument should contain only ASCII characters')
ValueError: string argument should contain only ASCII characters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 63, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 330, in downloadyt
    await query.reply_document(f"./{result['fulltitle']}.mp3",force_document=False,reply_markup=ReplyKeyboardRemove())
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 1580, in reply_document
    return await self._client.send_document(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/messages/send_document.py", line 178, in send_document
    media = utils.get_input_media_from_file_id(document, FileType.DOCUMENT)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/utils.py", line 51, in get_input_media_from_file_id
    raise ValueError(
ValueError: Failed to decode "./Brahms Lullaby 🎶 Best for Sleepy Baby |  Love Light.mp3". The value does not represent an existing local file, HTTP URL, or valid file id.
```

#error

**Comment by lmjaedentai** [comment]
restrictfilename = true
