### ISSUE TITLE
Anti spam in dict

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#69]
![Screenshot_2023-03-05-14-22-42-14_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/63090071/222945192-f7f95cdd-4b3f-476c-9aa0-0c303cb6d930.jpg)

❌ Telegram says: [420 FLOOD_WAIT_X] - A wait of 41 seconds is required (caused by "messages.EditMessage")
```py
Traceback (most recent call last):
  File "main.py", line 63, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 214, in on_message
    await typing.edit(f'📘 **[{i}](https://www.oxfordlearnersdictionaries.com/definition/english/{search.replace(" ","%20")})**{result}\n‎ ')
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2772, in edit_text
    return await self._client.edit_message_text(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 41 seconds is required (caused by "messages.EditMessage")
```

**Comment by lmjaedentai** [comment]
https://http.cat/429
```py
        for i in rawtext:
            global previous
            if i == previous: #antispam
                return await app.send_photo(message.chat.id,'https://http.cat/429')
            else:
                previous = i
```
