### ISSUE TITLE
Unknown json decode error in dict 

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#70]
![Screenshot_2023-03-05-14-25-08-33_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/63090071/222945285-030c38a0-6fdd-46e0-a4a7-c696b2ed488a.jpg)

❌ Expecting value: line 1 column 1 (char 0)
```py
Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 63, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 209, in on_message
    result = check_definition(i)
  File "main.py", line 176, in check_definition
    return check_definition(newsearch,second='spelling')
  File "main.py", line 162, in check_definition
    raw = r.json()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lmjaedentai** [comment]
```py
return f'\n\n👉🏻  refer [Meriam Webster Dictionary](https://www.merriam-webster.com/dictionary/{search})'+'\n\n\n👲🏻**中文注释**  '+chinese(search)
```
