### ISSUE TITLE
Air pollution index keyerror in /w

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#76]
❌ 'coord'

```py
Traceback (most recent call last):
  File "main.py", line 62, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 463, in sendweather
    response = requests.get(f"http://api.openweathermap.org/data/2.5/air_pollution?appid=c19ed679efd0dd0f4afdaa12325d2f17&lat={raw['coord']['lat']}&lon={raw['coord']['lon']}")
KeyError: 'coord'
```

**Comment by lmjaedentai** [comment]
#80
