### ISSUE TITLE
var `search` invalid in 404 url button

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#77]
probably bcos no `search.replace(' ','%20')`

❌ Telegram says: [400 BUTTON_URL_INVALID] - The button url is invalid (caused by "messages.SendMedia")

```py
Traceback (most recent call last):
  File "main.py", line 62, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 245, in dictionary
    return await app.send_photo(message.chat.id,'https://http.cat/404',reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("🔎 Try Google.",url=f'https://www.google.com/search?q=define%20{search}')]]))
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/messages/send_photo.py", line 170, in send_photo
    r = await self.invoke(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] - The button url is invalid (caused by "messages.SendMedia")
```

**Comment by lmjaedentai** [comment]
```py
.... url=f"https://www.google.com/search?q=define%20{search.replace(' ','%20')}")]]))
```
c effects in future
