### ISSUE TITLE
Fail err handling in /dict

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#78]
![image](https://user-images.githubusercontent.com/63090071/223914865-cb12b990-3b12-415f-8316-111593ae6037.png)
![image](https://user-images.githubusercontent.com/63090071/223914875-a7bd51fc-73bb-4c28-8992-7e80e93a718a.png)

❌ Expecting value: line 1 column 1 (char 0)

```py
Traceback (most recent call last):
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 62, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 243, in dictionary
    result = check_definition(search)
  File "main.py", line 160, in check_definition
    raw = r.json()
  File "/home/runner/billy-telegram/venv/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lmjaedentai** [comment]
jric noob

**Comment by lmjaedentai** [comment]
jric noob
