### ISSUE TITLE
Gif fail handling in dict

### ISSUE THREAD

**Issue by lmjaedentai** [lmjaedentai/billy-telegram#82]
❌ 'NoneType' object has no attribute 'lower'

```py
Traceback (most recent call last):
  File "main.py", line 62, in err_inner
    await func(app,message,**kwargs)
  File "main.py", line 199, in on_message
    search = message.text.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```
![Screenshot_2023-04-17-20-59-53-48_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/63090071/232498843-b64863ca-6cdf-4a1d-bedb-55d1117029f2.jpg)

**Comment by lmjaedentai** [comment]
Not applicable: only admin can send GIFs in dict grp
